llm-random/llm-random

research/conditional/train/cc_train.py

C4 was not working because the vocab size was accidentally changed to a smaller number
- Answer: yes
- Answer: yes
- Answer: [link to Neptune](https://app.neptune.ai/pmtest/llm-efficiency/e/LLMEF-5780)
- Answer: yes
- Answer: yes
- Answer: yes
7. Are there no …

make vocab bigger

---

lizrd/scripts/grid.py

n/a
- Answer:yes
- Answer:yes
- Answer:n/a
- Answer:yes
- Answer:yes
- Answer:yes
- Answer:yes
- Answer:yes …

Bind datasets cache folder on entropy gpu

---

research/conditional/moe_layers/cont_moe_designs/common_weighted_parameter_matrices.py
research/conditional/moe_layers/cont_moe_designs/separate_weighted_parameter_matrices.py

I forgot to change cache name after merging different MR
- Answer: yes
- Answer: yes
- Answer: na
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
8. …

fix updated cache function name

---

lizrd/scripts/grid.py
lizrd/scripts/grid_utils.py
research/conditional/train/cc_train.py
research/conditional/utils/misc_tools.py

Currently when we run grid it spawns new process which runs cc_train. This PR changes this behaviour, so in localhost it runs in the same process. It enables easier local debugging session as we can run json specified files.
- Answer: yes
- Answer: yes
- Answer: NA
- Answer: yes
- Answer: yes
6. Is there documentation …

Run experiment in localhost in the same process

---

lizrd/scripts/grid_utils.py

todo
- Answer: yes
- Answer: yes
- Answer: no, its a bug fix
- Answer: yes
- Answer:
- Answer: no need
- Answer: yes
8. Are all functions placed in …

Fixed imports problem

---

lizrd/core/llm.py

Layers were missing an info
- Answer: yes
- Answer: yes
- Answer: na
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
8. Are all functions placed in …

add layer info

---

lizrd/scripts/grid.py

title self-explanatory
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes, no task needed
8. Are all functions …

do not copy code locally

---

lizrd/datasets/wikibookdata.py

n/a
- Answer: y
- Answer: y
- Answer: n
- Answer: y
- Answer: y
- Answer: y
- Answer: y
- Answer: y
9. Is …

Suppress chmod (datasets permissions fixing) errors

---

research/conditional/train/cc_train.py
research/conditional/utils/argparse.py
research/conditional/utils/model_utils.py

Deprecate 'granularity_expert_config' args option - now the code works like it's always set to true.
- Answer: yes
- Answer: yes
- Answer: [link](https://app.neptune.ai/o/pmtest/org/llm-random/runs/details?viewId=99e7a7a3-88ac-4dbc-ba85-ce682752f44c&detailsTab=metadata&shortId=LLMRANDOM-45&type=run&compare=CzA0EYg&lbViewUnpacked=true&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode …

Mp remove granularity config

---

research/conditional/utils/conditional_trainer.py

After refactors dataloaders return tuples, also loss is returned as tuple. I had to make changes that acount for it to make `hack_for_batch_size` work. I also removed decoding in the step 0 (it takes unnecessarily long time in case of hack for batch size)
- Answer: yes
- Answer: yes
- Answer: [Link to Neptune](https://app.neptune.ai/o/pmtest/org/llm-efficiency/runs/details?viewId=98a55dc0-aa23-4c1a-a622-93ec989d9ab3&detailsTab=cha …

fix hack for batch size

---

lizrd/datasets/wikibookdata.py

todo
- Answer:y
- Answer:y
- Answer:n
- Answer:y
- Answer:y
- Answer:y
- Answer:[trello](https://trello.com/c/RSClcqkj/183-try-fixing-installing-requirements-s …

Fix pickling dataset

---

research/conditional/utils/model_utils.py

todo
- Answer:y
- Answer:y
- Answer:[klik](https://app.neptune.ai/o/pmtest/org/llm-random/runs/table?viewId=9a003555-1583-4771-8c45-9e07a892b9b7&detailsTab=metadata&shortId=LLMRANDOM-457&dash=charts&type=run&compare=CzBsBoEZKA&chartFilter=step)
- Answer:y
- Answer:y
6. Is there documentation for arguments and complex …

Break to fix chungus mixed precision

---

lizrd/scripts/grid.py
lizrd/scripts/grid_utils.py

Passing folder for cache was badly handled. I moved getting path to huggingface datasets funciont 
- Answer: yes
- Answer: yes
- Answer: na
- Answer: yes
- Answer: yes 
- Answer: yes 
7. Are there no temporary solutions in the code? Should a task be added to …

moved dataset_cache to function 

---

lizrd/scripts/run_exp_remotely.sh
lizrd/scripts/sync_with_remote.py
lizrd/support/code_versioning_support.py
requirements.txt

Runs code remotely by:
rsyncing to remote (lightweight, only do lizrd and research)
running code there
- Answer: yes
- Answer: yes
- Answer: no, not the point
- Answer:yes
- Answer: yes
- Answer: yes
7. Are there no temporary solutions in the code? Should a …

run experiments on cluster from local machine

---

research/conditional/moe_layers/continuous_moe.py

Need to add eps to not divide by 0.
- Answer: y
- Answer: y
- Answer: na
- Answer: y
- Answer: y
- Answer: y
- Answer: y
8. Are all functions placed in …

fix n_experts == 1 cont moe

---

lizrd/scripts/grid.py

title
- Answer: y
- Answer: y
- Answer:no point
- Answer:y
- Answer:y
- Answer:y
- Answer:y
- Answer:y
9. Is …

Main disallow no yamls

---

research/conditional/tests/test_integrated.py
research/conditional/train/configs/test/test_baseline.yaml

Itegration tests that run toy model on CPU, within unit tests
- Answer: y
- Answer: y
- Answer: y
- Answer: y
- Answer: y
- Answer: y
- Answer: y
8. Are all …

Integration tests

---

lizrd/scripts/grid.py
lizrd/scripts/run_exp_remotely.sh
lizrd/support/logging.py
research/conditional/tests/test_integrated.py
research/conditional/utils/argparse.py

title
- Answer: y
- Answer: y
- Answer: [link](https://app.neptune.ai/o/pmtest/org/llm-random/runs/details?viewId=99f374ec-39cd-48c4-ac55-0f8f7c35500c&detailsTab=metadata&shortId=LLMRANDOM-589&type=run&lbViewUnpacked=true&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=false&query=((%60sys%2Fowner%60%3Astring …

upload config to neptune

---

lizrd/support/sync_with_remote.py

todo
- Answer: y
- Answer: y
- Answer: no point
- Answer: y
- Answer: y
- Answer: y
- Answer: y
- Answer: y …

Main change access remotely

---

lizrd/scripts/run_exp_remotely.sh
lizrd/support/sync_with_remote.py
research/conditional/train/configs/test/test_baseline.yaml

- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: …

reduce test and make variable names clearer

---

lizrd/scripts/grid.py
lizrd/scripts/grid_utils.py

refactor grid so it is more clear
this is extracted from the now withdrawn multiple yamls PR
- Answer: yes
- Answer: yes
- Answer: no point
- Answer: yes
- Answer: yes
- Answer: yes
7. Are there no temporary solutions in the code? Should a task be added to …

refactor grid.py for clarity

---

research/conditional/utils/conditional_trainer.py

Convention is that if user sets decoding_logging_steps = 0  then we don't decode.
- Answer: y 
- Answer: y 
- Answer: na
- Answer: y 
- Answer:y 
- Answer: y  …

decoding fixed

---

.github/pull_request_template.md

After this PR all PRs will look like this:

template improve

---

lizrd/scripts/grid_utils.py

We encountered problems using shared huggingface cache. This PR introduces way to different hf cache for each user on one of clusters we use.

changed chache path athena

---

research/conditional/train/cc_train.py
research/conditional/utils/conditional_trainer.py

save weights every n steps, do not overwrite, safe for multiple exps in the same dir

---

lizrd/scripts/grid.py
lizrd/scripts/run_exp_remotely.sh
lizrd/support/code_versioning.py
lizrd/support/misc.py
lizrd/support/sync_and_version.py
research/conditional/tests/test_integrated.py
research/conditional/utils/argparse.py

it was not logged before. This is fixed by this pr
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
- Answer: yes
8. Are …

log git branch

---

research/conditional/train/configs/baselines/common.yaml
research/conditional/train/configs/baselines/gpt/common.yaml
research/conditional/train/configs/baselines/gpt/medium.yaml
research/conditional/train/configs/baselines/gpt/mini.yaml
research/conditional/train/configs/baselines/gpt/small.yaml

todo
- [] Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
- [] Are all variables set with logical defaults that are backward compatible?
- [] I attached link to neptune if it was necessary
- [] Have you successfully executed the linter and tests?
- [] Are all functions concise and don't require splitting?
- [] Is there documentation for arguments and complex logic?
- [] Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
- [] Are all functions placed in appropriate files?
- [] Is the PR name meaningful and descriptive?
- [] Is PR description provided, or unnecessary?
- [] If I made changes to the requirements or anything related to the Singularity image I did generate new …

Add gpt configs

---

.gitignore
lizrd/scripts/grid.py

do not write full config to tmp since its remote and clashes with other runs

---

lizrd/text/datasets.py
research/conditional/train/cc_train.py
research/datasets.py

As in PR name. We need this for C4 intergration tests.

small  c4 added

---

lizrd/support/misc.py

- [x ] Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
- [ x] Are all variables set with logical defaults that are backward compatible?
- [ x] I attached link to neptune if it was necessary
- [x ] Have you successfully executed the linter and tests?
- [x ] Are all functions concise and don't require splitting?
- [ x] Is there documentation for arguments and complex logic?
- [x ] Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
- [x ] Are all functions placed in appropriate files?
- [x ] Is the PR name meaningful and descriptive?
- [x ] Is PR description provided, or unnecessary?

verbose hash check

---

.github/pull_request_template.md
lizrd/support/sync_and_version.py

fix rsync script with proxyjump

---

research/conditional/train/configs/baselines/gpt/expert_choice/medium.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/small.yaml

add yamls for expert choice
- [ x] Is this PR focused on a single feature without the possibility of being divided into smaller PRs?

add expert choice baselines

---

lizrd/support/sync_and_version.py

print what errors occured in rsync in case of exception

---

research/conditional/utils/layer_manager.py

based on https://discuss.pytorch.org/t/unexpected-execution-time-difference-for-identical-operations-on-gpu/188681/6

profile code execution times using CUDA events

---

research/conditional/train/cc_train.py
research/conditional/train/configs/baselines/gpt/expert_choice/medium.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/small.yaml
research/conditional/utils/argparse.py
research/conditional/utils/conditional_trainer.py

fix eval, change naming to consistent with codebase

---

research/conditional/utils/argparse.py
research/conditional/utils/conditional_trainer.py

fix default decoding interval

---

lizrd/core/llm.py
lizrd/core/test_llm.py
research/conditional/utils/argparse.py
research/conditional/utils/model_utils.py

Simplify code for attention and add flash attention support

Jk_flash_attn

---

lizrd/core/llm.py
research/conditional/utils/model_utils.py

Remove legacy attn

---

research/conditional/utils/conditional_trainer.py

as in https://trello.com/c/W8UqQtrY

delete legacy bugged bert loss

---

research/conditional/train/cc_train.py

Mp data distributed

---

research/conditional/moe_layers/continuous_moe.py
research/conditional/train/cc_train.py
research/conditional/train/configs/baselines/mot_dynamic_gs.yaml
research/conditional/utils/argparse.py
research/conditional/utils/conditional_trainer.py

Mp dynamic groupsize

---

research/conditional/utils/conditional_trainer.py

jesus save me

---

.github/workflows/run_tests_and_checks.yml
research/conditional/tests/test_integrated.py

disable integration test

---

research/conditional/utils/conditional_trainer.py

remove bugged function

---

research/conditional/train/configs/baselines/gpt/base.yaml
research/conditional/train/configs/baselines/gpt/granularity/base.yaml
research/conditional/train/configs/baselines/gpt/granularity/medium.yaml
research/conditional/train/configs/baselines/gpt/granularity/mini.yaml
research/conditional/train/configs/baselines/gpt/granularity/small.yaml

Jk granularity configs

---

research/conditional/moe_layers/expert_choice.py
research/conditional/train/cc_train.py
research/conditional/utils/argparse.py
research/conditional/utils/conditional_trainer.py
research/conditional/utils/model_utils.py

group_size for MOE implemented

---

.github/workflows/run_tests_and_checks.yml
requirements.txt

bump 'datasets' lib and restore tests

---

research/conditional/moe_layers/continuous_moe.py
research/conditional/utils/argparse.py
research/conditional/utils/model_utils.py

allow taking softmax over experts during MoT emit phase

---

lizrd/text/test_combinations.py
research/conditional/tests/test_integrated.py

Now unit tests take 0.2s instead of 4 minutes xdd

Mark some tests as heavy

---

lizrd/scripts/grid_utils.py

Truly one of the `minor_fixes` @maciek-pioro 

fix datasets cache argument handover

---

lizrd/scripts/grid.py
lizrd/scripts/grid_utils.py

Finding out you messed up your config after it loaded in Atena after 10 hours can be frustrating. I say: No More!

check arguments with a parser before submitting a job

---

research/conditional/moe_layers/expert_choice.py

Remove bugged 🚑 🤔

---

research/conditional/moe_layers/expert_choice.py
research/conditional/tests/test_expert_choice.py
research/conditional/train/configs/experiments/expert_choice/compare_bmm_einsum.yaml
research/conditional/train/configs/experiments/expert_choice/run_mini_on_laptop.yaml
research/conditional/utils/argparse.py
research/conditional/utils/model_utils.py

[neptune](https://app.neptune.ai/o/pmtest/org/llm-random/runs/compare?viewId=9a15aa36-1063-49c4-807d-53393abb118a&detailsTab=dashboard&dashboardId=99e799d0-c13b-46d6-83f8-d1dfbc4e44e1&shortId=LLMRANDOM-2795&dash=loss-detailed-99e799d0-c13b-46d6-83f8-d1dfbc4e44e1&type=run&lbViewUnpacked=true&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=false&query=&compare=EwdgnCA0CMQ)

Torch bmm implementation

---

research/conditional/utils/conditional_trainer.py
research/conditional/utils/layer_manager.py

Add possibility to have logging heavy disabled

add logging changes

---

sparsity-base.def

wget curl install

---

lizrd/core/llm.py
lizrd/core/test_misc.py
research/conditional/utils/model_utils.py

This PR refactors `chungus` in the way that model does not have references to the same object in its descendants (it is needed by FSDP).
Also restored `chungus` test.

chungus cakc refactor

---

lizrd/core/llm.py
research/conditional/moe_layers/continuous_moe.py
research/conditional/tests/test_layer_manager.py
research/conditional/utils/layer_manager.py

Log statistics for residual stream and residual block updates

log activation norms

---

lizrd/core/llm.py
research/conditional/utils/layer_manager.py

ordered dict containing ff and attention had the same name 2 times - this anihilated the attention layer

fix model creation

---

research/blanks/model.py

Blanks in the same sequence accumulate changes to embedding and encoder_output from other blanks (previously, they just added it to preblank)

Residual and add_embeding fix

---

research/conditional/moe_layers/continuous_moe.py

bfloat16 decreased precision of calculations, so assert tolerance should be decresed

fix assert

---

lizrd/text/tokenizers.py
research/blanks/argparse.py
research/blanks/datasets.py
research/blanks/loss.py
research/blanks/model.py
research/blanks/packer.py
research/blanks/test_tokenizers.py
research/blanks/test_utils.py
research/blanks/tokenizers.py
research/blanks/train.py
research/blanks/trainer.py
research/blanks/utils.py

Makes it possible for different blanks to be separate tokens and have different embeddings.
- [LINK](https://app.neptune.ai/o/pmtest/org/llm-random/runs/compare?viewId=9aa8f618-f156-40ad-90e8-02d74360ea27&detailsTab=metadata&shortId=LLMRANDOM-3904&dash=charts&type=run&compare=MwNgrMA0CMQ&chartFilter=eval)

Multiple blanx tokens

---

research/blanks/argparse.py
research/blanks/datasets.py
research/blanks/packer.py
research/blanks/test_utils.py
research/blanks/train.py
research/blanks/trainer.py
research/blanks/utils.py

Make option to calculate loss only for the last blank

Kc make blanks loss mask

---

research/blanks/trainer.py

Fix saving weights in blanx

---

research/conditional/utils/conditional_trainer.py

fix eval in the case of grad accumulation

---

research/blanks/argparse.py
research/blanks/datasets.py
research/blanks/packer.py
research/blanks/train.py

Add option to insert blanks without cutting input

---

research/blanks/trainer.py

Always log the difference between last blank and preblank

---

research/conditional/moe_layers/expert_choice.py
research/conditional/train/configs/baselines/gpt/dense/large.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/base.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/common.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/dense/large.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/16/base.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/16/large.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/16/medium.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/16/mini.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/16/small.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/4/base.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/4/large.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/4/medium.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/4/mini.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/granularity/4/small.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/large.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/medium.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/mini.yaml
research/conditional/train/configs/baselines/gpt/expert_choice/small.yaml
research/conditional/train/configs/experiments/expert_choice/compare_bmm_einsum.yaml
research/conditional/train/configs/experiments/expert_choice/compare_compile.yaml
research/conditional/train/configs/experiments/expert_choice/run_mini_on_laptop.yaml
research/conditional/utils/layer_manager.py

- Fixed heavy logging in expert choice
- More timing in expert choice
- Reduced one permute
- Fixed configs
[Neptune](https://app.neptune.ai/o/pmtest/org/llm-random/runs/details?viewId=9a15aa36-1063-49c4-807d-53393abb118a&detailsTab=metadata&shortId=LLMRANDOM-4149&type=run&compare=CwBhCYBoEZgdiA&path=block_3%2Ffeedforward%2Ftime%2F&attribute=plot_0)

Logging in expert choice

---

README.md
research/conditional/train/cc_train.py
research/conditional/utils/argparse.py
research/conditional/utils/check_args.py
research/conditional/utils/conditional_trainer.py
research/conditional/utils/model_utils.py

This PR adds pytorch `profiler` to training loop. The changes are transparent for users who do not want to use it. 
[Neptune link](https://app.neptune.ai/o/pmtest/org/llm-random/runs/compare?viewId=standard-view&detailsTab=dashboard&dashboardId=9aa21d7d-37cf-4658-a724-91610708c674&shortId=LLMRANDOM-4230&dash=step-9aa21d7d-37cf-4658-a724-91610708c674&type=run&compare=CwRg7AbANArATEA) for comparison for with and without idle profiler context.

added traces

---

research/blanks/test_utils.py
research/blanks/utils.py

numpy 1.26 deprecates `np.bool` and suggest to change it to `bool`.

Fix bool numpy

---

research/conditional/train/configs/baselines/gpt/dense/mini_eight_blocks.yaml

Add another model size to yamls

Add new yaml for mini 8 layers

---

lizrd/scripts/grid.py

set gpu for dgx s.t. we are given the true A100

hardcode gpu for ideas

---

lizrd/text/packers.py
lizrd/text/test_combinations.py
research/conditional/train/cc_train.py
research/conditional/utils/model_utils.py
research/datasets.py

Change initialization of datasets s.t. FSDP doesn't hang up so often. Datasets are now created *after* the creation of dataloaders. We achieve this by passing `dataset_maker` instead of `dataset` and creating a property, which works by initializing the dataset the first time this field is accessed.

JK Fast FSDP

---

.gitignore
lizrd/scripts/make_argparse_schema.py
research/blanks/trainer.py

Add a script for creating yaml / json schemas from argparse. It is a simple, dirty solution that will probably only be used by me, so I don't expect the reviewer to be too strict.
- See description.

Add creating schemas

---

research/conditional/moe_layers/token_choice.py
research/conditional/tests/test_token_choice.py
research/conditional/utils/model_utils.py

todo
[Link](https://app.neptune.ai/o/pmtest/org/llm-random/runs/compare?viewId=standard-view&detailsTab=metadata&shortId=LLMRANDOM-5068&dash=charts&type=run&path=monitoring%2Fa56bb492%2F&attribute=gpu_memory&compare=KwBgbAHANAjEA&chartFilter=step&query=(sys%2Fid%3Astring%20%3D%20%22LLMRANDOM-5069%22)%20OR%20(sys%2Fid%3Astring%20%3D%20%22LLMRANDOM-5068%22)&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=true&lbViewUnpacked=true)

Fix token choice

---

lizrd/train/checkpointing.py
lizrd/train/train_utils.py
research/conditional/moe_layers/expert_choice.py

Changes the code so that it's possible to do checkpointing shenanigans (e.g. reusing a mask in checkpointing's second forward pass). Implements reusing a mask in expert choice.
- Could be divided into two PRs, however I think it would be unnecessary and harmful (it's easier to show the whole concept works in a single PR).
[CLICK](https://app.neptune.ai/o/pmtest/org/llm-random/runs/compare?viewId=9aae9724-c7a5-44b3-a894-d7bc9d7bd4df&detailsTab=metadata&shortId=LLMRANDOM-3842&dash=charts&type=run&path=loss_interval&attribute=1&compare=MwNgHCA0CMMKxyA&chartFilter=loss)
- 3927 is new code + no checkpointing + 2 gpus
- 3904 is new code + checkpointing + 2 gpus
- 3853 is new code + no checkpointing
- 3842 is new code + checkpointing
- 3687 is old code + no checkpointing
- 3686 is old code + …

Expert choice checkpointing

---

research/conditional/utils/model_utils.py

Ficed chungus not working with FSDP

Chungus fix

---

research/conditional/moe_layers/token_choice.py
research/conditional/tests/test_expert_choice.py
research/conditional/tests/test_token_choice.py
research/conditional/utils/model_utils.py

Has Token Choice router in higher precision.

Switch router higher precision

---

lizrd/core/test_misc.py
research/conditional/utils/conditional_trainer.py
research/conditional/utils/model_utils.py

Revert chungus changes that happened over the last couple of weeks because they're not compatible with some features.

Revert chungus changes

---

research/conditional/moe_layers/_token_choice_deprecated.py
research/conditional/moe_layers/token_choice.py
research/conditional/tests/test_token_choice.py
research/conditional/utils/argparse.py
research/conditional/utils/layer_manager.py
research/conditional/utils/model_utils.py

Implement topk (k!=1) in token choice

---

research/conditional/utils/layer_manager.py

Fix logging in fsdp

---

README.md

New Readme. Checklist is unnecessary

Replace README

---

research/conditional/utils/model_utils.py

For Mamba to work with FSDP gradient_accumulation_steps, we have to wrap Mamba individually in FSDP layer (add "Mamba" to fsdp_modules_to_wrap)

Add Mamba to get_classes_from_module_names

---

research/conditional/train/configs/experiments/mamba_dff_exp/moemamba_10_2.yaml
research/conditional/train/configs/experiments/mamba_dff_exp/moemamba_2_10.yaml
research/conditional/train/configs/experiments/mamba_dff_exp/moemamba_4_8.yaml
research/conditional/train/configs/experiments/mamba_dff_exp/moemamba_6_6.yaml
research/conditional/train/configs/experiments/mamba_dff_exp/moemamba_8_4.yaml
research/conditional/utils/argparse.py
research/conditional/utils/model_utils.py

Expand param in mamba

---

research/conditional/utils/layer_manager.py

- Remove requirement to hard-code every layer name for logging
[Neptune](https://app.neptune.ai/o/pmtest/org/llm-random/runs/details?viewId=9ac46a51-c84e-442d-963c-ac6a3a8af3f3&detailsTab=metadata&shortId=LLMRANDOM-7128&type=run&compare=OwRgTAHANCNA&path=.&query=((%60sys%2Fowner%60%3Astring%20%3D%20%22kkrol%22))%20AND%20(%60sys%2Fid%60%3Astring%20%3D%20%22LLMRANDOM-7128%22)&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=true&lbViewUnpacked=true)

LayerManager log everything

---

README.md
lizrd/scripts/generate_gpu_max_batch_size_report.py
lizrd/support/sync_and_version.py
research/blanks/configs/scratchpad/example.yaml
research/blanks/configs/scratchpad/less_embeddings.yaml
research/conditional/tests/test_integrated.py

Fix some refs to old config path

---

lizrd/grid/infrastructure.py
lizrd/grid/prepare_configs.py
lizrd/grid/setup_arguments.py
lizrd/scripts/grid.py
lizrd/scripts/grid_utils.py
lizrd/scripts/tests/test_yaml_handling.py
lizrd/support/misc.py
lizrd/test/test_grid.py

This PR logically splits some functions related to grid into few files in newly created `grid` folder:
- infrastructure contains defualt values on the clusters
- prepare_configs contains loading and merging configs from multiple sources
- setup_arguments contains setup arugments related function
It depends on https://github.com/llm-random/llm-random/pull/368

separate_functions

---

lizrd/grid/infrastructure.py
lizrd/grid/prepare_configs.py
lizrd/scripts/grid.py
lizrd/scripts/grid_utils.py
lizrd/test/test_grid.py

Tested on LocalBackend, DGX and Entropy (entropy failed due to dataset lock, which is after the scope of this PR)
[Neptune for DGX and Entopy](https://app.neptune.ai/o/pmtest/org/llm-random/runs/details?viewId=9ac46a51-c84e-442d-963c-ac6a3a8af3f3&detailsTab=metadata&shortId=LLMRANDOM-7675&type=run&compare=GwDgDA7ANATFCMBmMUCsBOBX7aA&lbViewUnpacked=true&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=true&query=((%60sys%2Fowner%60%3Astring%20%3D%20%22kkrol%22))%20AND%20(%60sys%2Fid%60%3Astring%20CONTAINS%20%22LLMRANDOM-767%22))

Kkrol grid suggestions

---

lizrd/grid/infrastructure.py

Update common directory path in AthenaBackend

---

lizrd/scripts/grid.py

If we have api keys in env we pass them

get_api_keys_from_env

---

lizrd/scripts/run_exp_remotely.sh
lizrd/support/code_versioning.py
submit_experiment.py

Submitting run exp remotely uses new vresioning since this PR

refactor run exp remotely

---

configs/experiments/expert_choice/run_mini_on_laptop.yaml
configs/experiments/test_new_refactor/test_init.yaml
research/conditional/moe_layers/moe_gating.py
research/conditional/moe_layers/token_choice.py
research/conditional/tests/test_token_choice.py

Ii's working now.
[Neptune link](https://app.neptune.ai/o/pmtest/org/llm-random/runs/compare?viewId=99f79ace-8d2e-4454-824e-1d95bd4e481d&dash=-loss-interval-1-step-9aaea80a-268f-4f2e-b13f-799ef22747e6&query=((%60sys%2Fowner%60%3Astring%20%3D%20%22jahulas%22))%20AND%20(%60args%2Fname%60%3Astring%20%3D%20%22init_grid%22)%20AND%20((%60sys%2Ftags%60%3AstringSet%20CONTAINS%20%22granularity%3D4%22))&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=true&lbViewUnpacked=true)

Fixed topk>1 in switch

---

lizrd/grid/infrastructure.py

onfrastructure config update

---

sparsity-head.def

Fix missing mamba_requirements.txt

Make singularity great again

---

lizrd/grid/infrastructure.py
lizrd/test/test_grid.py

Athena will now be 2x slower than other clusters for big experiments

Change dataset path on athena

---

lizrd/grid/prepare_configs.py
lizrd/grid/utils.py
research/template/tests/test_integrated.py
research/template/train/train.py
research/template/utils/argparse.py
research/template/utils/check_args.py
research/template/utils/layer_manager.py
research/template/utils/misc_tools.py
research/template/utils/model_utils.py
research/template/utils/trainer.py

Template project to clone for future schizo-experiments. Main idea is to make conditional less cluttered

Make template project

---

configs/experiments/relative_lr/base_relative_lr.yaml
lizrd/grid/utils.py

Fixes:
- base config
- dicts print without spaces in singularity command

Kc fix relative lr

---

configs/experiments/relative_lr/medium_relative_all.yaml
research/conditional/train/cc_train.py
research/conditional/utils/argparse.py

Add relative init scale support in code

Relative init scale

---

lizrd/core/initialization.py
lizrd/core/llm.py
research/conditional/utils/argparse.py
research/template/utils/argparse.py

Fix truncated normal initialization 

Truncated normal initialization fix

---

configs/mot/base_32E.yaml
lizrd/core/llm.py
research/conditional/train/cc_train.py
research/conditional/utils/argparse.py

[This commit of @Simontwice](https://github.com/llm-random/llm-random-cemetery/commit/1fd1bcc27ade089f1ad5b2cfd0bbfe9fa72ca443) made available specifying each block separately, so in order to run MoT we need to add it to our repo. 

Make MoT runningable again

---

README.md

Initializing new project in readme

---

lizrd/train/load_and_save_model.py
research/conditional/train/cc_train.py
research/conditional/utils/argparse.py
research/conditional/utils/conditional_trainer.py

This PR changes the way checkpoint saving works. Now, a new checkpoint is saved on every interval.

Fix checkpoint saving

---

lizrd/train/load_and_save_model.py

fixed fsdp checkpoint loading:
neptune:
https://app.neptune.ai/o/pmtest/org/llm-random/runs/compare?viewId=9cf2b9cd-2b26-41c4-b83c-7e0e3b45bc3d&dash=dashboard&dashboardId=-loss-interval-1-step-9aaea80a-268f-4f2e-b13f-799ef22747e6&compare=IwZg7ALATANCPCA

fixed FSDP checkpoint loading

---

lizrd/core/distributed.py
lizrd/train/load_and_save_model.py
research/conditional/train/cc_train.py
research/conditional/utils/argparse.py
research/conditional/utils/conditional_trainer.py

Log grads and updates in FSDP

---

lizrd/core/distributed.py
lizrd/train/load_and_save_model.py
research/conditional/train/cc_train.py
research/conditional/utils/argparse.py
research/conditional/utils/conditional_trainer.py

revert mp bugged code

---

.gitignore
lizrd/support/logging.py
research/conditional/utils/conditional_trainer.py
research/conditional/utils/misc_tools.py

Added job init and job end logs.
Example of new logs on neptune exp run: https://app.neptune.ai/o/pmtest/org/llm-random-tests/runs/details?viewId=9a15c4c2-79b1-4509-9f98-9edd0595f46f&detailsTab=metadata&shortId=LLMTST-2625&type=run

Logging slurm job id +

---

research/conditional/utils/model_utils.py

zloss and lb_loss fixed from mean to sum
neptune: [link](https://app.neptune.ai/o/pmtest/org/llm-random/runs/compare?viewId=9d3637bd-4acb-485d-9a7a-ee90dc5d674a&dash=dashboard&dashboardId=-loss-interval-1-step-9aaea80a-268f-4f2e-b13f-799ef22747e6&compare=IwdgrATAbANMcPsIA)

load_balancing_loss + zloss fix

---

research/conditional/utils/conditional_trainer.py

fix fsdp loss

---

lizrd/support/logging.py
research/conditional/utils/conditional_trainer.py

Fix logging slurm info if n_gpu > 1

---

research/conditional/utils/conditional_trainer.py

Fix all reduce error

---

research/conditional/utils/model_utils.py

fixes effective_dff_x param set by hard to 4
extracted math code for easier logic testing:
```
dmodel = 512
expansion_rate = 4
effective_dff_x = 2
granularity = 2
total_experts_width = dmodel * effective_dff_x * expansion_rate
n_experts = expansion_rate * granularity
effective_dff = effective_dff_x * dmodel
expert_size = total_experts_width / n_experts
assert expert_size == int(expert_size)
expert_size = int(expert_size)
routing_top_k = effective_dff / expert_size
topk_fraction = routing_top_k / n_experts
assert 0.0 <= topk_fraction <= 1.0
routing_top_k = int(routing_top_k)
print(f'routing_top_k: {routing_top_k}')
print(f'expert_size: {expert_size}')
print(f'n_experts: {n_experts}')
print(f'topk_fraction: {topk_fraction}')
print(f'total_experts_width: {total_experts_width}') …
```

fix determine_moe_args

---

lizrd/grid/__main__.py

sleep depriviation PR
sleep(5) reduced to sleep(1) when pushing sequential experiments grid, this still works and is much less problematic for running a huge grid.

less sleep

---

lizrd/support/logging.py
lizrd/support/misc.py
research/conditional/train/cc_train.py
research/conditional/utils/conditional_trainer.py

This pr fixes counting model parameters. Instead of getting count from torch model, it calculates from args using equations (brrr math). There are model configurations that aren't handled, in such case 1 is returned as model param count. This is because we don't want to kill new modules and 1 schould be strange enough to be recognised as wrong. Calculating from torch is still there and printed as sanity check. Main feature is fixing token to param ratio, and token_per_active x-axis on loss charts in neptune.
What I'm not sure about are the names of the new args variables, args that are logged to neptune. I tried to be descriptive, but shout out if sth is confusing.

Fix active param count

---

research/conditional/utils/argparse.py

Uses eval function to compute learning rate. This will enable to for example us exponent with base 2 as lr

calculate learning_rate

---

configs/examples/bs_rampup_example.yaml
lizrd/support/misc.py
lizrd/support/test_misc.py
research/batch_size_rampup_config.py
research/conditional/train/cc_train.py
research/conditional/utils/conditional_trainer.py
research/datasets.py
research/test_research_datasets.py

Jk_rampup_calc_n_tokens

---

research/conditional/train/cc_train.py

Jk_fix_slides_2

---

research/conditional/train/cc_train.py

[Neptune link](https://app.neptune.ai/o/pmtest/org/llm-random/runs/compare?viewId=9a15aa36-1063-49c4-807d-53393abb118a&detailsTab=metadata&dash=charts&type=run&compareChartsFilter=lr&query=(sys%2Fid%3Astring%20%3D%20%22LLMRANDOM-22287%22)%20OR%20(sys%2Fid%3Astring%20%3D%20%22LLMRANDOM-22286%22)%20OR%20(sys%2Fid%3Astring%20%3D%20%22LLMRANDOM-22285%22)%20OR%20(sys%2Fid%3Astring%20%3D%20%22LLMRANDOM-22275%22)&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&suggestionsEnabled=false&lbViewUnpacked=true&compare=EwjsFYBoEYAYZkA)

Jk_constrained_grid_22_11

---

lizrd/core/llm.py

there are 2 (copy - pased Attention classesin lizrd llm) this PR deletes unnecessary code.

code cleanup

---

lizrd/core/llm.py

Make tensors contiguous to make flash attention faster. Comparison of code with/without contiguous, where contiguous is 38% faster: [Neptune](https://app.neptune.ai/o/pmtest/org/llm-random/runs/table?viewId=9a15aa36-1063-49c4-807d-53393abb118a&dash=table&query=(sys%2Fid%3Astring%20%3D%20%22LLMRANDOM-23306%22)%20OR%20(sys%2Fid%3Astring%20%3D%20%22LLMRANDOM-23307%22)&lbViewUnpacked=true&sortBy=%5B%22sys%2Fcreation_time%22%5D&sortFieldType=%5B%22datetime%22%5D&sortFieldAggregationMode=%5B%22auto%22%5D&sortDirection=%5B%22descending%22%5D&compareChartsFilter=step&compare=EwZhAYDYBoEYg). This was found by @maciek-pioro

Jk contig attn
